[package]
name = "memfault-ssf"
version = "0.1.0"
edition = "2021"
description = "Supporting crate for the Memfault memfaultd embedded Linux agent"
homepage = "https://github.com/memfault/memfaultd"
documentation = "https://docs.memfault.com/"
license-file = "License.txt"
readme = "README.md"
repository = "https://github.com/memfault/memfaultd"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
