[package]
name = "memfaultd"
version = "0.1.0"
edition = "2021"
autobins = false
rust-version = "1.65"

[[bin]]
name = "memfaultd"
path = "src/bin/memfaultd.rs"

[[bin]]
name= "memfaultctl"
path= "src/bin/memfaultctl.rs"

[[bin]]
name= "memfault-core-handler"
path= "src/bin/memfault-core-handler.rs"

[dependencies]
memfaultc-sys = { path= "../memfaultc-sys" }
argh = "0.1.10"
cfg-if = "1.0.0"
chrono = { version = "0.4.23", features = ["serde"]}
ciborium = { version = "0.2.1", optional = true}
eyre = "0.6.8"
goblin = { version = "0.7", optional = true, default-features = false, features = ["elf32", "elf64", "std"] }
libc = "0.2.138"
log = "0.4.17"
prctl = { version = "1.0.0", optional = true}
psm = { version = "0.1.21", optional = true }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json" ] }
rmp-serde = { version = "1.1.1", optional = true }
rmpv = { version = "1.0.0", optional = true }
scroll = { version = "0.11", optional = true }
serde = { version = "1.0.150", features = ["derive"] }
serde_bytes = "0.11.8"
serde_json = "1.0.89"
serde_repr = "0.1"
shuteye = "0.3.3"
signal-hook = "0.3.14"
stderrlog = "0.5.4"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
tempfile = "3.3.0"
thiserror = "1.0.38"
threadpool = { version = "1.8.1"}
urlencoding = "2.1.2"
uuid = { version = "1.3.0", features = ["v4", "serde"] }
once_cell = "1.17.0"
fs_extra = "1.3.0"
flate2 = { version = "1.0.28", default-features = false, features = ["zlib"] }
take_mut = "0.2.2"
itertools = "0.10.5"
governor = { version = "0.5.1", default-features = false, features = ["std"], optional = true}
nix = { version = "0.26.2", default-features = false, features = ["process", "signal", "poll"]}
kernlog = { version = "0.3.1", optional = true }
tiny_http = {version = "0.12.0" }
crc = "3.0.1"
crc-catalog = "2.2.0"
regex= { version = "1.10.2", optional = true}
nom = "7.1.3"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.15.1", optional = true }

[dev-dependencies]
tempfile = "3.3.0"
mockall = "0.11.3"
rstest = "0.16.0"
goblin = { version = "0.7", default-features = false, features = ["elf32", "elf64", "std", "endian_fd"] }
insta = {version= "1.26.0", features= ["json", "redactions"]}
zip = { version = "0.6.3", default-features = false, features = ["deflate"] }
hex = "0.4.3"
rand = "0.8.5"
nom = "7.1.3"

[features]
default = ["coredump", "collectd", "logging", "log-to-metrics", "systemd", "rust-tls" ]
coredump = [
    "memfaultc-sys/coredump",
    "dep:prctl",
    "dep:procfs",
    "dep:psm",
    "dep:kernlog",
    "dep:ciborium",
    "dep:goblin",
    "dep:scroll"
]
collectd = []
swupdate = ["memfaultc-sys/swupdate"]
logging = ["dep:governor", "dep:rmp-serde", "dep:rmpv"]
systemd = ["memfaultc-sys/systemd"]
rust-tls = ["reqwest/rustls-tls"]
openssl-tls = ["reqwest/native-tls"]
openssl-vendored-tls = ["reqwest/native-tls-vendored"]
log-to-metrics = ["dep:regex"]
