# Mirrors the block that meta-memfault-example/conf/local.conf.sample documents
MEMFAULT_DELTA_OTA = "1"
IMAGE_ROOTFS_SIZE = "258048"
IMAGE_OVERHEAD_FACTOR = "1"
IMAGE_ROOTFS_MAXSIZE = "262144"
IMAGE_CLASSES:append = " image_types_zchunk"
IMAGE_FSTYPES:append = " ext4.zck ext4.zck.zckheader"
